name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /home/ubuntu/Handcar-final
          git pull origin main
          source venv/bin/activate
          pip install -r requirements.txt

          #  Write .env file using GitHub secrets
          echo "CLOUDINARY_CLOUD_NAME=${{ secrets.CLOUDINARY_CLOUD_NAME }}" > .env
          echo "CLOUDINARY_API_KEY=${{ secrets.CLOUDINARY_API_KEY }}" >> .env
          echo "CLOUDINARY_API_SECRET=${{ secrets.CLOUDINARY_API_SECRET }}" >> .env

          python manage.py migrate
          deactivate

          sudo rm -f /etc/nginx/sites-available/Handcar
          sudo rm -f /etc/nginx/sites-enabled/Handcar
          sudo rm -f /etc/nginx/sites-enabled/default

          sudo chown -R ubuntu:www-data /home/ubuntu/Handcar-final
          sudo chmod -R u+rwX,g+rX /home/ubuntu/Handcar-final
          sudo chmod g+x /home/ubuntu
          sudo chmod 660 /home/ubuntu/Handcar-final.sock || true

          sudo systemctl restart gunicorn
          sudo nginx -t && sudo systemctl restart nginx
